packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
  msgpackr-extract: true
  workerd: true
  nucleo-ui-fill-18: set this to true or false
  nucleo-ui-outline-18: set this to true or false
catalog:
  zod: ^4.5.4
  typescript: ^7.0.2
  "@types/node": ^26.4.1
  varlock: 1.18.0
  "@orpc/server": ^1.15.0
  "@orpc/openapi": ^1.15.0
  "@orpc/zod": ^1.15.0
  better-auth: 1.7.7
  next-themes: ^0.4.6
  react: ^19.2.8
  react-dom: ^19.2.8
  sonner: ^2.0.8
  tailwindcss: ^4.3.3
  "@orpc/client": ^1.15.0
  "@types/react": ^19.2.18
  "@types/react-dom": ^19.2.7
  drizzle-orm: 1.0.0-rc.4
  "@neaps/tide-database": 0.9.20260907
  "@neaps/tide-predictor": 0.11.0
  effect: 4.0.0
